"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

const hosts=["facebook.com","fb.watch","instagram.com","youtube.com","youtu.be","tiktok.com","x.com","twitter.com"];
function validUrl(value:string){try{const u=new URL(value);return u.protocol==="https:" && hosts.some(h=>u.hostname===h||u.hostname.endsWith("."+h));}catch{return false}}

export default function MediaManager({items}:{items:any[]}){
 const [rows,setRows]=useState(items); const [form,setForm]=useState({title:"",description:"",category:"",url:""});
 async function change(id:string,status:string){const s=createClient();const r=await s.from("media_items").update({status,published_at:status==="approved"?new Date().toISOString():null}).eq("id",id);if(!r.error)setRows(rows=>rows.map(x=>x.id===id?{...x,status}:x));}
 async function addExternal(e:React.FormEvent){e.preventDefault();if(!form.title||!validUrl(form.url))return alert("Enter a title and a valid supported social-media HTTPS link.");const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {data,error}=await s.from("media_items").insert({owner_id:user.id,title:form.title,description:form.description,category:form.category,media_kind:"video",source_type:"external",source_url:form.url,rights_confirmed:true,download_allowed:false,status:"pending"}).select("id,title,media_kind,status,created_at").single();if(error)return alert(error.message);setRows(x=>[data,...x]);setForm({title:"",description:"",category:"",url:""});}
 return <section className="mt-6 rounded-2xl bg-white p-5 shadow-sm">
 <h2 className="text-lg font-bold">Media moderation & social links</h2><p className="text-sm text-slate-500">Paste an authorized public link. Malvis embeds supported platforms or sends viewers to the original post.</p>
 <form onSubmit={addExternal} className="mt-4 grid gap-3 rounded-xl border p-4"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Video title" className="rounded-lg border px-3 py-2"/><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Category" className="rounded-lg border px-3 py-2"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" className="rounded-lg border px-3 py-2"/><input required type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://youtube.com/... or https://facebook.com/..." className="rounded-lg border px-3 py-2"/><button className="rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white">Submit social video for approval</button></form>
 <div className="mt-4 space-y-3">{rows.map(i=><div key={i.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{i.title}</p><p className="text-xs text-slate-500">{i.media_kind} · {i.status}</p></div>{i.status==="pending"&&<div className="flex gap-2"><button onClick={()=>change(i.id,"approved")} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Approve</button><button onClick={()=>change(i.id,"rejected")} className="rounded-lg bg-red-600 px-3 py-2 text-sm font-semibold text-white">Reject</button></div>}</div></div>)}</div>
 </section>;
}