"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function OfferManager({businessId,initialProducts,initialServices}:{businessId:string;initialProducts:any[];initialServices:any[]}){
 const [kind,setKind]=useState<"products"|"services">("products");const [name,setName]=useState("");const [price,setPrice]=useState("");const [message,setMessage]=useState("");const [items,setItems]=useState({products:initialProducts,services:initialServices});const s=createClient();
 async function add(e:React.FormEvent){e.preventDefault();setMessage("");const {data,error}=await s.from(kind).insert({business_id:businessId,name,price_ngn:price?Number(price):null}).select().single();if(error){setMessage(error.message);return;}setItems({...items,[kind]:[data,...items[kind]]});setName("");setPrice("");setMessage("Added successfully.");}
 async function remove(id:string){const {error}=await s.from(kind).delete().eq("id",id);if(error){setMessage(error.message);return;}setItems({...items,[kind]:items[kind].filter((x:any)=>x.id!==id)});}
 return <div><div className="flex gap-2"><button type="button" onClick={()=>setKind("products")} className={kind==="products"?"rounded-lg bg-black px-3 py-2 text-sm text-white":"rounded-lg border px-3 py-2 text-sm"}>Products</button><button type="button" onClick={()=>setKind("services")} className={kind==="services"?"rounded-lg bg-black px-3 py-2 text-sm text-white":"rounded-lg border px-3 py-2 text-sm"}>Services</button></div><form onSubmit={add} className="mt-4 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input required className="rounded-xl border p-3" placeholder={kind==="products"?"Product name":"Service name"} value={name} onChange={e=>setName(e.target.value)}/><input className="rounded-xl border p-3" type="number" min="0" placeholder="Price (NGN)" value={price} onChange={e=>setPrice(e.target.value)}/><button className="rounded-xl bg-indigo-600 px-5 py-3 text-white">Add</button></form>{message&&<p className="mt-3 text-sm text-slate-600">{message}</p>}<div className="mt-5 space-y-2">{items[kind].map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-xl border p-3"><span>{x.name} · {x.price_ngn==null?"Contact":"NGN "+Number(x.price_ngn).toLocaleString()}</span><button type="button" onClick={()=>remove(x.id)} className="text-sm text-red-600">Delete</button></div>)}</div></div>;
}